### ISSUE TITLE
[Patch] add support for key authentication

### ISSUE THREAD

**Issue by LazyT** [mikemvk/QSshSocket#1]
Hi Mikhail,

nice wrapper, but unfortunately missing key auth. Maybe the attached [patch](https://github.com/mikemvk/QSshSocket/files/2274183/qsshsocket.patch.txt)
 is usefull to implement?

btw: I don't see the disconnect() signal is emitted?

Thanks for your work...

**Comment by mikemvk** [comment]
Thanks! Its very usefull.
I will implement disconnect() later.
